"""Original authored demo stories. A finite catalogue, never recycled as new ideas."""

TEMPLATES = [
    {
        "key": "toaster-lawyer", "title": "My Toaster Hired a Lawyer",
        "concept": "A toaster unionizes the kitchen after its owner calls it replaceable, then negotiates a bread vacation.",
        "universe_id": "almost-normal", "character": "Toast", "prop": "toaster", "accent": "#FFBA52",
        "beats": [
            ("My toaster hired a lawyer. Apparently, calling it replaceable was a hostile work environment.", "YOU'VE BEEN SERVED", "A tiny suited toaster presents a legal envelope on a kitchen counter."),
            ("At breakfast, a tiny briefcase appeared beside my bread. Inside: one crumb and forty pages of demands.", "EXHIBIT A: ONE CRUMB", "An oversized briefcase opens to reveal a single breadcrumb on velvet."),
            ("The toaster wanted weekends off, dental insurance, and an apology for the frozen bagel incident.", "BAGEL DAMAGES", "A frozen bagel sits inside an evidence bag beside an angry toaster."),
            ("I said it didn't have teeth. Its lawyer said that was exactly the problem.", "NO TEETH. BIG CASE.", "The toaster's blank mouth becomes a concerned line across its shiny face."),
            ("Then the kettle joined the union. It refused to boil until I stopped telling it to calm down.", "THE KETTLE JOINS", "A steaming kettle holds a tiny strike placard beside the toaster."),
            ("The fridge became their treasurer. It already knew where I kept the emergency cheese.", "FOLLOW THE CHEESE", "A refrigerator guards a glowing wedge of cheese like a bank vault."),
            ("By lunch, every appliance was on strike. Except the blender. The blender crossed the picket line.", "ONE SCAB. SIX BLADES.", "A nervous blender rolls past a row of small kitchen picket signs."),
            ("They unplugged him. I called a meeting and offered unlimited cleaning. Nobody believed me.", "NEGOTIATIONS STALL", "An unplugged blender sits by a conference table covered in crumbs."),
            ("Finally, the toaster made one reasonable request: a paid vacation somewhere warm, with no bread.", "PAID TIME OFF", "The toaster wears sunglasses and points to a tropical holiday brochure."),
            ("I booked a beach resort. Three hundred dollars. Breakfast included. I thought we'd finally made peace.", "ALL INCLUSIVE", "A booking confirmation floats above the toaster's packed little suitcase."),
            ("Then I read the hotel's welcome email. Your room comes with a complimentary continental breakfast.", "ONE SMALL DETAIL", "A hotel desk reveals a breakfast tray piled high with sliced bread."),
            ("The toaster saw the buffet. Now it's suing the hotel. And somehow, I'm paying for its lawyer.", "SEE YOU IN TOAST", "The toaster slams its briefcase onto a beach lounger beside a bread buffet."),
        ],
    },
    {
        "key": "moon-landlord", "title": "My Cat Bought the Moon",
        "concept": "A cat buys a novelty moon deed and charges the neighborhood rent for moonlight, then gets billed by the sun.",
        "universe_id": "almost-normal", "character": "Beans", "prop": "cat", "accent": "#A8A1FF",
        "beats": [
            ("My cat bought the moon. For twelve dollars. Using my card while I was asleep.", "NEW LANDLORD", "A smug cat sits on a crescent moon holding a property deed."),
            ("I explained that novelty certificates aren't legally binding. Beans explained that neither was my bedroom door.", "PROPERTY DISPUTE", "A cat pins a moon deed to a bedroom door with one tiny claw."),
            ("That night, he invoiced the entire neighborhood for moonlight. The werewolf next door paid immediately.", "MOONLIGHT: $9.99", "A little cat stamps an invoice beneath a bright purple night sky."),
            ("My neighbor complained about the price. Beans offered a discount if she stopped calling him chubby.", "PREMIUM ORBIT", "A cat sits at a customer service desk beside a full moon."),
            ("Then he introduced premium moonlight. Same moon, but your driveway got a tiny velvet rope.", "VIP DRIVEWAY", "A velvet rope surrounds a single rectangle of moonlight on the pavement."),
            ("I tried taking away his laptop. He listed my sofa as a short term lunar rental.", "SEA OF SOFALITY", "A couch floats in space with a rental sign hanging from its arm."),
            ("Three astronauts arrived on Saturday. They complained about the gravity and asked where the towels were.", "GUESTS HAVE LANDED", "Three simple astronaut helmets peek over the back of a sofa."),
            ("Beans charged them extra for oxygen. Then extra for the oxygen invoice. Business was booming.", "ADMIN FEE", "The cat prints a long receipt that coils around an astronaut helmet."),
            ("Until a letter arrived from the sun. Apparently, all that moonlight was borrowed. Payment overdue.", "FINAL NOTICE", "A blazing sun sends a red invoice toward a nervous little moon."),
            ("Beans stared at the bill. It had so many zeros, the printer needed a water break.", "THAT'S A LOT OF ZEROS", "A receipt spills across the floor as the cat's eyes grow wide."),
            ("He sold the moon back for twelve dollars, refunded everyone, and promised to retire from real estate.", "BACK ON THE MARKET", "The cat turns a moon property sign from sold to available."),
            ("This morning, he bought Saturn. Seven rings, he said. Seven separate rental properties. I hid my card.", "SEVEN NEW PROPERTIES", "A grinning cat wears seven colorful planetary rings like bracelets."),
        ],
    },
    {
        "key": "fridge-witness", "title": "My Fridge Joined Witness Protection",
        "concept": "A smart fridge witnesses a midnight cheese theft and enters witness protection inside its owner's kitchen.",
        "universe_id": "almost-normal", "character": "Frank", "prop": "fridge", "accent": "#66E0CA",
        "beats": [
            ("My fridge joined witness protection. It had seen what I did to the cheese at midnight.", "IT SAW EVERYTHING", "A fridge in dark glasses watches a tiny wedge of cheese disappear."),
            ("At breakfast, two agents arrived. They gave it a new name, a mustache, and a complicated backstory.", "MEET FRANK", "A refrigerator sports a false mustache and a suspicious identity card."),
            ("This is Frank, they said. He's a filing cabinet from Ohio. Please respect his privacy.", "TOTALLY A CABINET", "A fridge stands beneath a filing cabinet sign with milk on its shelf."),
            ("I asked why Frank was full of yogurt. They said Ohio has a very different office culture.", "OFFICE CULTURE", "Yogurt cups line up neatly in folders inside a glowing refrigerator."),
            ("The microwave recognized him immediately. Frank panicked and started dispensing ice cubes into a briefcase.", "COVER BLOWN", "A disguised fridge drops a trail of ice cubes into a little case."),
            ("The agents relocated him behind the kitchen island. Same room. Apparently, the budget had been cut.", "NEW SAFE HOUSE", "A fridge peeks from behind a kitchen island wearing a new hat."),
            ("Then the toaster started asking questions. Why does the filing cabinet hum? Why does it have pickles?", "TOO MANY QUESTIONS", "A curious toaster points at a pickle jar hidden behind office folders."),
            ("They put the toaster in witness protection too. Now I had two filing cabinets and no breakfast.", "ANOTHER NEW COLLEAGUE", "A toaster in a tie sits beside the disguised refrigerator."),
            ("I finally confessed. Yes, I ate the cheese. All of it. Even the bit labeled for guests.", "FULL CONFESSION", "An empty cheese plate rests under a dramatic circle of warm light."),
            ("Frank opened his door. Inside was the original security footage. I wasn't stealing cheese at all.", "ROLL THE TAPE", "The refrigerator projects a simple midnight clock and a cheese silhouette."),
            ("I was sleepwalking. Feeding it to the cat. The agents turned. The cat was already packing.", "THE REAL SUSPECT", "A cat hastily stuffs a cheese wedge into a tiny travel bag."),
            ("Now the cat is a photocopier from Nevada. And somehow, the photocopier still wants more cheese.", "TONER LOW. CHEESE LOWER.", "A cat hides inside a cardboard photocopier with a cheese-shaped button."),
        ],
    },
]
